GenConMedico/Models/Entities/Paciente.cs
namespace GenConMedico.Models.Entities
{
    public class Paciente
    {
        public int Id { get; set; }
        public string CPF { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;
        public DateTime DataNascimento { get; set; }
        public InformacoesComplementaresPaciente? InformacoesComplementares { get; set; }
        public ICollection<MonitoramentoPaciente> Monitoramentos { get; set; } = null!;
        public ICollection<Consulta> Consultas { get; set; } = null!;
    }
}

GenConMedico/ViewModels/Medicos/AdicionarViewModel.cs
namespace GenConMedico.ViewModels.Medicos;

public class AdicionarViewModel
{
    public string CRM { get; set; } = string.Empty;
    public string Nome { get; set; } = string.Empty;
}

GenConMedico/ViewModels/Pacientes/AdicionarPacienteViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GenConMedico.ViewModels.Pacientes
{
    public class AdicionarPacienteViewModel
    {
        public string CPF { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;
        
        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }
    }
}

GenConMedico/ViewModels/Pacientes/AdicionarViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GenConMedico.ViewModels.Pacientes
{
    public class AdicionarViewModel
    {
        public string CPF { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;

        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }

    }
}

GenConMedico/ViewModels/Pacientes/EditarPacienteViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GenConMedico.ViewModels.Pacientes
{
    public class EditarPacienteViewModel
    {
        public int Id { get; set; }
        public string CPF { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;
        
        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }
        public string? Alergias { get; set; }
        [Display(Name = "Medicamentos em Uso")]
        public string? MedicamentosEmUso { get; set; }
        [Display(Name = "Cirurgias Realizadas")]
        public string? CirurgiasRealizadas { get; set; }
    }
}

GenConMedico/ViewModels/Pacientes/EditarViewModal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace GenConMedico.ViewModels.Pacientes
{
    public class EditarViewModal
    {
        public int Id { get; set; }
        public string CPF { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;

        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }


        public string? Alergias { get; set; }

        [Display(Name = "Medicamento em Uso")]
        public string? MedicamentosEmUso { get; set; }
        [Display(Name = "Cirurgias Realizadas")]
        public string? CirurgiasRealizadas { get; set; }

    }
}

GenConMedico/ViewModels/Pacientes/ListarPacienteViewModal.cs
namespace GenConMedico.ViewModels.Pacientes
{
    public class ListarPacienteViewModal
    {
        public int Id { get; set; }
        public string CPF { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;

    }
}

GenConMedico/ViewModels/Pacientes/ListarPacienteViewModel.cs
namespace GenConMedico.ViewModels.Pacientes
{
    public class ListarPacienteViewModel
    {
        public int Id { get; set; }
        public string CPF { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;
    }
}

GenConMedico/Controllers/PacientesController.cs
using System.Text.RegularExpressions;
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using GenConMedico.Models.Contexts;
using GenConMedico.Models.Entities;
using GenConMedico.ViewModels.Pacientes;

namespace GenConMedico.Controllers
{
    public class PacientesController : Controller
    {
        private readonly GenConMedContext _context;
        private readonly IValidator<AdicionarPacienteViewModel> _adicionarPacienteValidator;
        private readonly IValidator<EditarPacienteViewModel> _editarPacienteValidator;

        private const int TAMANHO_PAGINA = 10;

        public PacientesController(GenConMedContext context, IValidator<AdicionarPacienteViewModel> adicionarPacienteValidator, IValidator<EditarPacienteViewModel> editarPacienteValidator)
        {
            _context = context;
            _adicionarPacienteValidator = adicionarPacienteValidator;
            _editarPacienteValidator = editarPacienteValidator;
        }

        public IActionResult Index(string filtro, int pagina = 1)
        {
            var medicos = _context.Pacientes.Where(x => x.Nome.Contains(filtro) || x.CPF.Contains(filtro))
                                            .Select(x => new ListarPacienteViewModel
                                            {
                                              Id = x.Id,
                                              CPF = x.CPF,
                                              Nome = x.Nome
                                            });

            ViewBag.Filtro = filtro;
            ViewBag.NumeroPagina = pagina;
            ViewBag.TotalPaginas = Math.Ceiling((decimal)medicos.Count() / TAMANHO_PAGINA);
            return View(medicos.Skip((pagina - 1) * TAMANHO_PAGINA).Take(TAMANHO_PAGINA));
        }

        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Adicionar(AdicionarPacienteViewModel dados)
        {
            var validacao = _adicionarPacienteValidator.Validate(dados);

            if(!validacao.IsValid)
            {
                validacao.AddToModelState(ModelState, string.Empty);
                return View(dados);
            }

            var paciente = new Paciente
            {
                CPF = Regex.Replace(dados.CPF, "[^0-9]", ""),
                Nome = dados.Nome,
                DataNascimento = dados.DataNascimento
            };

            _context.Pacientes.Add(paciente);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Editar(int id)
        {
            var paciente = _context.Pacientes.Find(id);

            if(paciente != null)
            {
                var informacoesComplementares = _context.InformacoesComplementaresPaciente.FirstOrDefault(x => x.IdPaciente == id);

                return View(new EditarPacienteViewModel
                {
                    Id = paciente.Id,
                    CPF = paciente.CPF,
                    Nome = paciente.Nome,
                    DataNascimento = paciente.DataNascimento,
                    Alergias = informacoesComplementares?.Alergias,
                    MedicamentosEmUso = informacoesComplementares?.MedicamentosEmUso,
                    CirurgiasRealizadas = informacoesComplementares?.CirurgiasRealizadas,
                });
            }

            return NotFound();
        }

         [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(int id, EditarPacienteViewModel dados)
        {
            var validacao = _editarPacienteValidator.Validate(dados);
            
            if(!validacao.IsValid)
            {
                validacao.AddToModelState(ModelState, string.Empty);
                return View(dados);
            }
            
            var paciente = _context.Pacientes.Find(id);

            if(paciente != null)
            {
                paciente.CPF = Regex.Replace(dados.CPF, "[^0-9]", "");
                paciente.Nome = dados.Nome;
                paciente.DataNascimento = dados.DataNascimento;

                var informacoesComplementares = _context.InformacoesComplementaresPaciente.FirstOrDefault(x => x.IdPaciente == id);

                if(informacoesComplementares == null)
                    informacoesComplementares = new InformacoesComplementaresPaciente();

                informacoesComplementares.Alergias = dados.Alergias;
                informacoesComplementares.MedicamentosEmUso = dados.MedicamentosEmUso;
                informacoesComplementares.CirurgiasRealizadas = dados.CirurgiasRealizadas;
                informacoesComplementares.IdPaciente = id;

                if (informacoesComplementares.Id > 0)
                    _context.InformacoesComplementaresPaciente.Update(informacoesComplementares);
                else
                    _context.InformacoesComplementaresPaciente.Add(informacoesComplementares);
                    
                _context.Pacientes.Update(paciente);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return NotFound();
        }

        public IActionResult Excluir(int id)
        {
            var paciente = _context.Pacientes.Find(id);

            if(paciente != null)
            {
                return View(new EditarPacienteViewModel
                {
                    Id = paciente.Id,
                    CPF = paciente.CPF,
                    Nome = paciente.Nome,
                    DataNascimento = paciente.DataNascimento
                });
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Excluir(int id, EditarPacienteViewModel dados)
        {          
            var paciente = _context.Pacientes.Find(id);

            if(paciente != null)
            {
                _context.Pacientes.Remove(paciente);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return NotFound();
        }

        public IActionResult Buscar(string filtro)
        {
            var pacientes = _context.Pacientes.Where(x => x.Nome.Contains(filtro) || x.CPF.Contains(filtro))
                                              .Take(10)
                                              .Select(x => new ListarPacienteViewModel
                                              {
                                                Id = x.Id,
                                                Nome = x.Nome,
                                                CPF = x.CPF
                                              });
            return Json(pacientes);
        }
    }
}

GenConMedico/Views/Pacientes/Adicionar.cshtml
@{
    ViewData["Title"] = "Paciente: Adicionar";
}

@model GenConMedico.ViewModels.Pacientes.AdicionarViewModel

<section class="content-header">
    <div class="contariner-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cadastrar paciente</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Adicionar">
                <div class="car">
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="CPF" class="control-label"></label>
                            <input asp-for="CPF" class="form-control" mask="999.999.999-99">
                            <span asp-validation-for="CPF" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label"></label>
                            <input asp-for="Nome" class="form-control">
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DataNascimento" class="control-label"></label>
                            <input asp-for="DataNascimento" class="form-control">
                            <span asp-validation-for="DataNascimento" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="card-footer text-right">
                    <button class="btn btn-primary" type="submit">Salvar</button>
                </div>
            </form>
        </div>
    </div>

</section>

GenConMedico/Views/Pacientes/Editar.cshtml
@model GenConMedico.ViewModels.Pacientes.EditarPacienteViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Editar paciente</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Editar">
                <div class="card">
                    <div class="card-body">
                        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                        <div class="form-group">
                            <label asp-for="CPF" class="control-label"></label>
                            <input asp-for="CPF" class="form-control" mask="999.999.999-99">
                            <span asp-validation-for="CPF" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label"></label>
                            <input asp-for="Nome" class="form-control">
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DataNascimento" class="control-label"></label>
                            <input asp-for="DataNascimento" class="form-control">
                            <span asp-validation-for="DataNascimento" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Alergias" class="control-label"></label>
                            <input asp-for="Alergias" class="form-control">
                            <span asp-validation-for="Alergias" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="MedicamentosEmUso" class="control-label"></label>
                            <input asp-for="MedicamentosEmUso" class="form-control">
                            <span asp-validation-for="MedicamentosEmUso" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="CirurgiasRealizadas" class="control-label"></label>
                            <input asp-for="CirurgiasRealizadas" class="form-control">
                            <span asp-validation-for="CirurgiasRealizadas" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col">
                                <a href="/pacientes/excluir/@Model.Id" class="btn btn-danger">Excluir</a>
                            </div>
                            <div class="col text-right">
                                <button class="btn btn-primary" type="submit">Salvar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

GenConMedico/Views/Pacientes/Excluir.cshtml
@model GenConMedico.ViewModels.Pacientes.EditarPacienteViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Excluir paciente</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="alert alert-danger">
        <span class="fas fa-warning"></span>
        Deseja realmente excluir o cadastro deste paciente?
    </div>
    <div class="row">
        <div class="col-12">
            <form asp-action="Excluir">
                <div class="card card-outline card-danger">
                    <div class="card-body">
                        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                        <div class="form-group">
                            <label asp-for="CPF" class="control-label"></label>
                            <input asp-for="CPF" class="form-control" mask="999.999.999-99" readonly>
                            <span asp-validation-for="CPF" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label"></label>
                            <input asp-for="Nome" class="form-control" readonly>
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="DataNascimento" class="control-label"></label>
                            <input asp-for="DataNascimento" class="form-control" readonly>
                            <span asp-validation-for="DataNascimento" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button class="btn btn-danger" type="submit">Excluir</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

GenConMedico/Views/Pacientes/Index.cshtml
@model IEnumerable<GenConMedico.ViewModels.Pacientes.ListarPacienteViewModel>

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Pacientes</h1>
            </div>
        </div>
    </div>
</section>

<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <form asp-action="Index">
                            <div class="input-group input-group-sm" style="width: 300px;">
                                <input type="text" class="form-control" placeholder="Buscar paciente" name="filtro" value="@ViewBag.Filtro">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>

                        <a href="/pacientes/adicionar" class="btn btn-outline-primary btn-sm">Novo paciente</a>
                    </div>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table table-head-fixed text-nowrap">
                        <thead>
                            <tr>
                                <th style="width: 200px;">CPF</th>
                                <th>Nome</th>
                                <th style="width: 40px;"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var m in Model)
                            {
                                <tr>
                                    <td mask="999.999.999-99">@m.CPF</td>
                                    <td>@m.Nome</td>
                                    <td>
                                        <a href="/pacientes/editar/@m.Id" class="btn btn-secondary btn-sm mr-1" title="Editar paciente">
                                            <span class="fas fa-edit"></span>
                                        </a>
                                        <a href="/monitoramento?idPaciente=@m.Id" class="btn btn-secondary btn-sm mr-1" title="Monitoramento de sinais vitais">
                                            <span class="fas fa-list"></span>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix">
                    @if(ViewBag.TotalPaginas > 0)
                    {
                        <ul class="pagination pagination-sm m-0 float-right">
                        @if(ViewBag.NumeroPagina > 1)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "Pacientes", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina - 1 })">
                                    &laquo;
                                </a>
                            </li>
                        }
                        <li class="page-item page-link">Página @ViewBag.NumeroPagina de @ViewBag.TotalPaginas</li>
                        @if(ViewBag.NumeroPagina < @ViewBag.TotalPaginas)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "Pacientes", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina + 1 })">
                                    &raquo;
                                </a>
                            </li>
                        }
                    </ul>
                    }
                </div>
            </div>
        </div>
    </div>
</div>