GenConMedico/Models/Entities/Consulta.cs
using GenConMedico.Models.Enums;

namespace GenConMedico.Models.Entities
{
    public class Consulta
    {
        public int Id { get; set; }
        public DateTime Data { get; set; }    
        public TipoConsulta Tipo { get; set; }
        public int IdPaciente { get; set; }
        public int IdMedico { get; set; }
        public Paciente Paciente { get; set; } = null!;
        public Medico Medico { get; set; } = null!;
    }
}

GenConMedico/ViewModels/Consultas/AdicionarConsultaViewModel.cs
using System.ComponentModel.DataAnnotations;
using GenConMedico.Models.Enums;

namespace GenConMedico.ViewModels.Consultas
{
    public class AdicionarConsultaViewModel
    {
        [DataType(DataType.Date)]
        public DateTime Data { get; set; }
        public TipoConsulta Tipo { get; set; }
        [Display(Name = "Paciente")]
        public int IdPaciente { get; set; }
        [Display(Name = "Médico")]
        public int IdMedico { get; set; }
    }
}

GenConMedico/ViewModels/Consultas/EditarConsultaViewModel.cs
using System.ComponentModel.DataAnnotations;
using GenConMedico.Models.Enums;

namespace GenConMedico.ViewModels.Consultas
{
    public class EditarConsultaViewModel
    {
        [DataType(DataType.Date)]
        public DateTime Data { get; set; }
        public TipoConsulta Tipo { get; set; }
        [Display(Name = "Paciente")]
        public int IdPaciente { get; set; }
        public string NomePaciente { get; set; } = string.Empty;
        [Display(Name = "Médico")]
        public int IdMedico { get; set; }
    }
}

GenConMedico/ViewModels/Consultas/ListarConsultaViewModel.cs
namespace GenConMedico.ViewModels.Consultas
{
    public class ListarConsultaViewModel
    {
        public int Id { get; set; }
        public string Paciente { get; set; } = string.Empty;
        public string Medico { get; set; } = string.Empty;
        public string Tipo { get; set; } = string.Empty;
        public DateTime Data { get; set; }
    }
}

GenConMedico/ViewModels/Medicos/AdicionarViewModel.cs
namespace GenConMedico.ViewModels.Medicos;

public class AdicionarViewModel
{
    public string CRM { get; set; } = string.Empty;
    public string Nome { get; set; } = string.Empty;
}

GenConMedico/ViewModels/Pacientes/AdicionarViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GenConMedico.ViewModels.Pacientes
{
    public class AdicionarViewModel
    {
        public string CPF { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;

        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }

    }
}

GenConMedico/Controllers/ConsultasController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GenConMedico.Models.Contexts;
using GenConMedico.Models.Entities;
using GenConMedico.Models.Enums;
using GenConMedico.ViewModels.Consultas;

namespace GenConMedico.Controllers
{
    public class ConsultasController : Controller
    {
        private readonly GenConMedContext _context;
        private readonly IValidator<AdicionarConsultaViewModel> _adicionarConsultaValidator;
        private readonly IValidator<EditarConsultaViewModel> _editararConsultaValidator;
        private const int TAMANHO_PAGINA = 10;

        public ConsultasController(GenConMedContext context, IValidator<AdicionarConsultaViewModel> adicionarConsultaValidator, IValidator<EditarConsultaViewModel> editararConsultaValidator)
        {
            _context = context;
            _adicionarConsultaValidator = adicionarConsultaValidator;
            _editararConsultaValidator = editararConsultaValidator;
        }

        public IActionResult Index(string filtro, int pagina = 1)
        {
            var consultas = _context.Consultas.Include(c => c.Paciente)
                                              .Include(c => c.Medico)
                                              .Where(c => c.Paciente.Nome.Contains(filtro) || c.Medico.Nome.Contains(filtro))
                                              .Select(c => new ListarConsultaViewModel
                                              {
                                                Id = c.Id,
                                                Paciente = c.Paciente.Nome,
                                                Medico = c.Medico.Nome,
                                                Data = c.Data,
                                                Tipo = c.Tipo == TipoConsulta.Eletiva ? "Eletiva" : "Urgência"
                                              });
            ViewBag.NumeroPagina = pagina;
            ViewBag.TotalPaginas = Math.Ceiling((decimal)consultas.Count() / TAMANHO_PAGINA);

            return View(consultas.Skip((pagina - 1) * TAMANHO_PAGINA).Take(TAMANHO_PAGINA));
        }

        public IActionResult Adicionar()
        {
            ViewBag.TiposConsulta = new [] {
                new SelectListItem { Text = "Eletiva", Value = TipoConsulta.Eletiva.ToString() },
                new SelectListItem { Text = "Urgência", Value = TipoConsulta.Urgencia.ToString() }
            };
            ViewBag.Medicos = _context.Medicos.OrderBy(x => x.Nome).Select(x => new SelectListItem { Text = x.Nome, Value = x.Id.ToString() });
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Adicionar(AdicionarConsultaViewModel dados)
        {
            var validacao = _adicionarConsultaValidator.Validate(dados);

            if(!validacao.IsValid)
            {
                ViewBag.TiposConsulta = new [] {
                    new SelectListItem { Text = "Eletiva", Value = TipoConsulta.Eletiva.ToString() },
                    new SelectListItem { Text = "Urgência", Value = TipoConsulta.Urgencia.ToString() }
                };
                ViewBag.Medicos = _context.Medicos.OrderBy(x => x.Nome).Select(x => new SelectListItem { Text = x.Nome, Value = x.Id.ToString() });
                validacao.AddToModelState(ModelState, string.Empty);
                return View(dados);
            }

            var consulta = new Consulta
            {
                Data = dados.Data,
                IdPaciente = dados.IdPaciente,
                IdMedico = dados.IdMedico,
                Tipo = dados.Tipo
            };

            _context.Consultas.Add(consulta);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Editar(int id)
        {
            var consulta = _context.Consultas.Include(x => x.Paciente)
                                             .FirstOrDefault(x => x.Id == id);
            
            if (consulta != null)
            {
                ViewBag.TiposConsulta = new [] {
                    new SelectListItem { Text = "Eletiva", Value = TipoConsulta.Eletiva.ToString() },
                    new SelectListItem { Text = "Urgência", Value = TipoConsulta.Urgencia.ToString() }
                };
                ViewBag.Medicos = _context.Medicos.OrderBy(x => x.Nome).Select(x => new SelectListItem { Text = x.Nome, Value = x.Id.ToString() });

                return View(new EditarConsultaViewModel
                {
                   IdMedico = consulta.IdMedico,
                   IdPaciente = consulta.IdPaciente,
                   NomePaciente = consulta.Paciente.Nome,
                   Data = consulta.Data,
                   Tipo = consulta.Tipo 
                });
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(int id, EditarConsultaViewModel dados)
        {
            var validacao = _editararConsultaValidator.Validate(dados);
            
            if(!validacao.IsValid)
            {
                ViewBag.TiposConsulta = new [] {
                    new SelectListItem { Text = "Eletiva", Value = TipoConsulta.Eletiva.ToString() },
                    new SelectListItem { Text = "Urgência", Value = TipoConsulta.Urgencia.ToString() }
                };
                ViewBag.Medicos = _context.Medicos.OrderBy(x => x.Nome).Select(x => new SelectListItem { Text = x.Nome, Value = x.Id.ToString() });
                validacao.AddToModelState(ModelState, string.Empty);
                return View(dados);
            }
            
            var consulta = _context.Consultas.Find(id);

            if(consulta != null)
            {
                consulta.Data = dados.Data;
                consulta.IdPaciente = dados.IdPaciente;
                consulta.IdMedico = dados.IdMedico;
                consulta.Tipo = dados.Tipo;
                _context.Consultas.Update(consulta);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return NotFound();
        }
    }
}

GenConMedico/Views/Consultas/Adicionar.cshtml
@model GenConMedico.ViewModels.Consultas.AdicionarConsultaViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Registrar consulta</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Adicionar">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="Data" class="control-label"></label>
                            <input asp-for="Data" class="form-control">
                            <span asp-validation-for="Data" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Tipo" class="control-label"></label>
                            <select asp-for="Tipo" class="form-control" asp-items="@ViewBag.TiposConsulta"></select>
                            <span asp-validation-for="Tipo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IdMedico" class="control-label"></label>
                            <select asp-for="IdMedico" class="form-control" asp-items="@ViewBag.Medicos"></select>
                            <span asp-validation-for="IdMedico" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IdPaciente" class="control-label"></label>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Buscar paciente" id="NomePaciente" readonly>
                                <div class="input-group-append">
                                    <button type="button" class="btn btn-default" id="BtnBuscarPaciente" data-toggle="modal" data-target="#ModalPacientes">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                            <input type="hidden" asp-for="IdPaciente" class="form-control" id="IdPaciente">
                            <span asp-validation-for="IdPaciente" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button class="btn btn-primary" type="submit">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<div class="modal" tabindex="-1" role="dialog" id="ModalPacientes">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    Buscar paciente
                </h5>
                <button class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Buscar paciente" id="TxtFiltro">
                            <div class="input-group-append">
                                <button class="btn btn-default" id="BtnBuscar">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-hover table-sm d-none" id="TbPacientes">
                    <thead>
                        <th style="width: 150px;">CPF</th>
                        <th>Nome</th>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
                <div class="alert alert-warning d-none" id="DivMensagem">Nenhum paciente localizado.</div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        function buscarPaciente() {
            if ($("#TxtFiltro").val().trim().length > 0) {
                $.getJSON("/pacientes/buscar?filtro="+ $("#TxtFiltro").val(), function(resultado) {
                    if (resultado.length > 0) {
                        var linhas = resultado.map(x => "<tr data-dismiss='modal' style='cursor: pointer;' title='Clique para selecionar' data-id='" + x.id + "'><td mask='999.999.999-99'>" + x.cpf +"</td><td>" + x.nome + "</td></tr>").join("");
                        $("#TbPacientes tbody").html(linhas);
                        $("td[mask]").each(function(e){
                            $(this).mask($(this).attr("mask"));
                        });
                        $("#TbPacientes tbody tr").click(function(){
                            var id = $(this).attr("data-id");
                            var nome = $(this).children()[1].innerText;
                            $("#IdPaciente").val(id);
                            $("#NomePaciente").val(nome);
                        });
                        $("#TbPacientes").removeClass("d-none");
                        $("#DivMensagem").addClass("d-none");
                    }
                    else {
                        $("#TbPacientes").addClass("d-none");
                        $("#DivMensagem").removeClass("d-none");
                    }
                });
            }
        }

        $("#TxtFiltro").keyup(function(e){
            if (e.keyCode === 13) {
                buscarPaciente();
            }
        });

        $("#BtnBuscar").click(function(){
            buscarPaciente();
        });
    </script>
}

GenConMedico/Views/Consultas/Editar.cshtml
@model GenConMedico.ViewModels.Consultas.EditarConsultaViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Editar consulta</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Editar">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="Data" class="control-label"></label>
                            <input asp-for="Data" class="form-control">
                            <span asp-validation-for="Data" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Tipo" class="control-label"></label>
                            <select asp-for="Tipo" class="form-control" asp-items="@ViewBag.TiposConsulta"></select>
                            <span asp-validation-for="Tipo" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IdMedico" class="control-label"></label>
                            <select asp-for="IdMedico" class="form-control" asp-items="@ViewBag.Medicos"></select>
                            <span asp-validation-for="IdMedico" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IdPaciente" class="control-label"></label>
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Buscar paciente" asp-for="NomePaciente" id="NomePaciente" readonly>
                                <div class="input-group-append">
                                    <button type="button" class="btn btn-default" id="BtnBuscarPaciente" data-toggle="modal" data-target="#ModalPacientes">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                            <input type="hidden" asp-for="IdPaciente" class="form-control" id="IdPaciente">
                            <span asp-validation-for="IdPaciente" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button class="btn btn-primary" type="submit">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

<div class="modal" tabindex="-1" role="dialog" id="ModalPacientes">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    Buscar paciente
                </h5>
                <button class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Buscar paciente" id="TxtFiltro">
                            <div class="input-group-append">
                                <button class="btn btn-default" id="BtnBuscar">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-hover table-sm d-none" id="TbPacientes">
                    <thead>
                        <th style="width: 150px;">CPF</th>
                        <th>Nome</th>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
                <div class="alert alert-warning d-none" id="DivMensagem">Nenhum paciente localizado.</div>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        function buscarPaciente() {
            if ($("#TxtFiltro").val().trim().length > 0) {
                $.getJSON("/pacientes/buscar?filtro="+ $("#TxtFiltro").val(), function(resultado) {
                    if (resultado.length > 0) {
                        var linhas = resultado.map(x => "<tr data-dismiss='modal' style='cursor: pointer;' title='Clique para selecionar' data-id='" + x.id + "'><td mask='999.999.999-99'>" + x.cpf +"</td><td>" + x.nome + "</td></tr>").join("");
                        $("#TbPacientes tbody").html(linhas);
                        $("td[mask]").each(function(e){
                            $(this).mask($(this).attr("mask"));
                        });
                        $("#TbPacientes tbody tr").click(function(){
                            var id = $(this).attr("data-id");
                            var nome = $(this).children()[1].innerText;
                            $("#IdPaciente").val(id);
                            $("#NomePaciente").val(nome);
                        });
                        $("#TbPacientes").removeClass("d-none");
                        $("#DivMensagem").addClass("d-none");
                    }
                    else {
                        $("#TbPacientes").addClass("d-none");
                        $("#DivMensagem").removeClass("d-none");
                    }
                });
            }
        }

        $("#TxtFiltro").keyup(function(e){
            if (e.keyCode === 13) {
                buscarPaciente();
            }
        });

        $("#BtnBuscar").click(function(){
            buscarPaciente();
        });
    </script>
}

GenConMedico/Views/Consultas/Index.cshtml
@model IEnumerable<GenConMedico.ViewModels.Consultas.ListarConsultaViewModel>

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Consultas</h1>
            </div>
        </div>
    </div>
</section>

<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <form asp-action="Index">
                            <div class="input-group input-group-sm" style="width: 300px;">
                                <input type="text" class="form-control" placeholder="Buscar consulta" name="filtro" value="@ViewBag.Filtro">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>

                        <a href="/consultas/adicionar" class="btn btn-outline-primary btn-sm">Nova consulta</a>
                    </div>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table table-head-fixed text-nowrap">
                        <thead>
                            <tr>
                                <th style="width: 100px;">Data</th>
                                <th>Paciente</th>
                                <th>Médico</th>
                                <th style="width: 40px;"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var c in Model)
                            {
                                <tr>
                                    <td>@c.Data.ToString("dd/MM/yyyy")</td>
                                    <td>@c.Paciente</td>
                                    <td>@c.Medico</td>
                                    <td>
                                        <a href="/consultas/editar/@c.Id" class="btn btn-secondary btn-sm mr-1" title="Editar consulta">
                                            <span class="fas fa-edit"></span>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix">
                    @if(ViewBag.TotalPaginas > 0)
                    {
                        <ul class="pagination pagination-sm m-0 float-right">
                        @if(ViewBag.NumeroPagina > 1)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "Consultas", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina - 1 })">
                                    &laquo;
                                </a>
                            </li>
                        }
                        <li class="page-item page-link">Página @ViewBag.NumeroPagina de @ViewBag.TotalPaginas</li>
                        @if(ViewBag.NumeroPagina < @ViewBag.TotalPaginas)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "Consultas", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina + 1 })">
                                    &raquo;
                                </a>
                            </li>
                        }
                    </ul>
                    }
                </div>
            </div>
        </div>
    </div>
</div>