GenConMedico/Models/Entities/Medico.cs
namespace GenConMedico.Models.Entities
{
    public class Medico
    {
        public int Id { get; set; }
        public string CRM { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;
        public ICollection<Consulta> Consultas { get; set; } = null!;
    }
}

GenConMedico/ViewModels/Medicos/AdicionarMedicoViewModel.cs
namespace GenConMedico.ViewModels.Medicos
{
    public class AdicionarMedicoViewModel
    {
        public string CRM { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;
    }
}

GenConMedico/ViewModels/Medicos/AdicionarViewModel.cs
namespace GenConMedico.ViewModels.Medicos;

public class AdicionarViewModel
{
    public string CRM { get; set; } = string.Empty;
    public string Nome { get; set; } = string.Empty;
}

GenConMedico/ViewModels/Medicos/EditarMedicoViewModel.cs
namespace GenConMedico.ViewModels.Medicos
{
    public class EditarMedicoViewModel
    {
        public int Id { get; set; }
        public string CRM { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;
    }
}

GenConMedico/ViewModels/Medicos/EditarViewModal.cs
namespace GenConMedico.ViewModels.Medicos;

public class EditarViewModal
{
    public int Id { get; set; }
    public string CRM { get; set; } = string.Empty;
    public string Nome { get; set; } = string.Empty;
}

GenConMedico/ViewModels/Medicos/ListarMedicoViewModel.cs
namespace GenConMedico.ViewModels.Medicos
{
    public class ListarMedicoViewModel
    {
        public int Id { get; set; }
        public string CRM { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;
    }
}

GenConMedico/ViewModels/Pacientes/AdicionarViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace GenConMedico.ViewModels.Pacientes
{
    public class AdicionarViewModel
    {
        public string CPF { get; set; } = string.Empty;
        public string Nome { get; set; } = string.Empty;

        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }

    }
}

GenConMedico/Controllers/MedicosController.cs
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Mvc;
using GenConMedico.Models.Contexts;
using GenConMedico.Models.Entities;
using GenConMedico.ViewModels.Medicos;

namespace GenConMedico.Controllers
{
    public class MedicosController : Controller
    {
        private readonly GenConMedContext _context;
        private readonly IValidator<AdicionarMedicoViewModel> _adicionarMedicoValidator;
        private readonly IValidator<EditarMedicoViewModel> _editarMedicoValidator;
        private const int TAMANHO_PAGINA = 10;

        public MedicosController(GenConMedContext context, IValidator<AdicionarMedicoViewModel> adicionarMedicoValidator, IValidator<EditarMedicoViewModel> editarMedicoValidator)
        {
            _context = context;
            _adicionarMedicoValidator = adicionarMedicoValidator;
            _editarMedicoValidator = editarMedicoValidator;
        }

        public IActionResult Index(string filtro, int pagina = 1)
        {
            var medicos = _context.Medicos.Where(x => x.Nome.Contains(filtro) || x.CRM.Contains(filtro))
                                          .Select(x => new ListarMedicoViewModel
                                          {
                                            Id = x.Id,
                                            CRM = x.CRM,
                                            Nome = x.Nome
                                          });

            ViewBag.Filtro = filtro;
            ViewBag.NumeroPagina = pagina;
            ViewBag.TotalPaginas = Math.Ceiling((decimal)medicos.Count() / TAMANHO_PAGINA);
            return View(medicos.Skip((pagina - 1) * TAMANHO_PAGINA).Take(TAMANHO_PAGINA));
        }

        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Adicionar(AdicionarMedicoViewModel dados)
        {
            var validacao = _adicionarMedicoValidator.Validate(dados);

            if(!validacao.IsValid)
            {
                validacao.AddToModelState(ModelState, string.Empty);
                return View(dados);
            }
            
            var medico = new Medico
            {
                CRM = dados.CRM,
                Nome = dados.Nome
            };

            _context.Medicos.Add(medico);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Editar(int id)
        {
            var medico = _context.Medicos.Find(id);

            if(medico != null)
            {
                return View(new EditarMedicoViewModel
                {
                    Id = medico.Id,
                    CRM = medico.CRM,
                    Nome = medico.Nome
                });
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(int id, EditarMedicoViewModel dados)
        {          
            var validacao = _editarMedicoValidator.Validate(dados);

            if(!validacao.IsValid)
            {
                validacao.AddToModelState(ModelState, string.Empty);
                return View(dados);
            }

            var medico = _context.Medicos.Find(id);

            if(medico != null)
            {
                medico.CRM = dados.CRM;
                medico.Nome = dados.Nome;
                _context.Medicos.Update(medico);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return NotFound();
        }

        public IActionResult Excluir(int id)
        {
            var medico = _context.Medicos.Find(id);

            if(medico != null)
            {
                return View(new ListarMedicoViewModel
                {
                    Id = medico.Id,
                    CRM = medico.CRM,
                    Nome = medico.Nome
                });
            }

            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Excluir(int id, ListarMedicoViewModel dados)
        {          
            var medico = _context.Medicos.Find(id);

            if(medico != null)
            {
                _context.Medicos.Remove(medico);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }

            return NotFound();
        }
    }
}

GenConMedico/Views/Medicos/Adicionar.cshtml
@model GenConMedico.ViewModels.Medicos.AdicionarMedicoViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Cadastrar médico</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Adicionar">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="CRM" class="control-label"></label>
                            <input asp-for="CRM" class="form-control">
                            <span asp-validation-for="CRM" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label"></label>
                            <input asp-for="Nome" class="form-control">
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer text-right">
                        <button class="btn btn-primary" type="submit">Salvar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

GenConMedico/Views/Medicos/Editar.cshtml
@model GenConMedico.ViewModels.Medicos.EditarMedicoViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Editar médico</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <form asp-action="Editar">
                <div class="card">
                    <div class="card-body">
                        <div class="text-danger" asp-validation-summary="ModelOnly"></div>

                        <div class="form-group">
                            <label asp-for="CRM" class="control-label"></label>
                            <input asp-for="CRM" class="form-control">
                            <span asp-validation-for="CRM" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label"></label>
                            <input asp-for="Nome" class="form-control">
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col">
                                <a href="/medicos/excluir/@Model.Id" class="btn btn-danger">Excluir</a>
                            </div>
                            <div class="col text-right">
                                <button class="btn btn-primary" type="submit">Salvar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

GenConMedico/Views/Medicos/Excluir.cshtml
@model GenConMedico.ViewModels.Medicos.ListarMedicoViewModel

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Excluir médico</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="alert alert-danger">
        <span class="fas fa-warning"></span>
        Deseja realmente excluir este cadastro?
    </div>
    <div class="row">
        <div class="col-12">
            <form asp-action="Excluir">
                <div class="card card-outline card-danger">
                    <div class="card-body">
                        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
                        <div class="form-group">
                            <label asp-for="CRM" class="control-label"></label>
                            <input asp-for="CRM" class="form-control" readonly>
                            <span asp-validation-for="CRM" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Nome" class="control-label"></label>
                            <input asp-for="Nome" class="form-control" readonly>
                            <span asp-validation-for="Nome" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="row">
                            <div class="col text-right">
                                <button class="btn btn-danger" type="submit">Excluir</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>

GenConMedico/Views/Medicos/index.cshtml
@model IEnumerable<GenConMedico.ViewModels.Medicos.ListarMedicoViewModel>

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Médicos</h1>
            </div>
        </div>
    </div>
</section>

<div class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between">
                        <form asp-action="Index">
                            <div class="input-group input-group-sm" style="width: 300px;">
                                <input type="text" class="form-control" placeholder="Buscar médico" name="filtro" value="@ViewBag.Filtro">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </form>

                        <a href="/medicos/adicionar" class="btn btn-outline-primary btn-sm">Novo médico</a>
                    </div>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table table-head-fixed text-nowrap">
                        <thead>
                            <tr>
                                <th style="width: 200px;">CRM</th>
                                <th>Nome</th>
                                <th style="width: 40px;"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var m in Model)
                            {
                                <tr>
                                    <td>@m.CRM</td>
                                    <td>@m.Nome</td>
                                    <td>
                                        <a href="/medicos/editar/@m.Id" class="btn btn-secondary btn-sm mr-1" title="Editar médico">
                                            <span class="fas fa-edit"></span>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix">
                    @if(ViewBag.TotalPaginas > 0)
                    {
                        <ul class="pagination pagination-sm m-0 float-right">
                        @if(ViewBag.NumeroPagina > 1)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "Medicos", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina - 1 })">
                                    &laquo;
                                </a>
                            </li>
                        }
                        <li class="page-item page-link">Página @ViewBag.NumeroPagina de @ViewBag.TotalPaginas</li>
                        @if(ViewBag.NumeroPagina < @ViewBag.TotalPaginas)
                        {
                            <li class="page-item">
                                <a class="page-link" href="@Url.Action("Index", "Medicos", new { Filtro = @ViewBag.Filtro, Pagina = @ViewBag.NumeroPagina + 1 })">
                                    &raquo;
                                </a>
                            </li>
                        }
                    </ul>
                    }
                </div>
            </div>
        </div>
    </div>
</div>